services:
  stackoverflow-db:
    image: postgres
    container_name: stackoverflow-db
    restart: on-failure
    env_file:
      - ./backend/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  stackoverflow-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - stackoverflow-db
    env_file:
      - ./backend/.env.dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    container_name: stackoverflow-backend
    command: yarn run dev
    restart: on-failure

volumes:
  postgres-data:
