services:
  stackoverflow-db:
    image: postgres
    container_name: stackoverflow-db
    restart: on-failure
    environment:
      POSTGRES_DB: stackoverflow-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  stackoverflow-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - stackoverflow-db
    environment:
      - NODE_ENV=development
      - DB_NAME=stackoverflow-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=stackoverflow-db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    container_name: stackoverflow-backend
    command: yarn run dev
    restart: on-failure

volumes:
  postgres-data:
