version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres-db
    restart: on-failure
    environment:
      POSTGRES_DB: stackoverflow_clone_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_NAME=stackoverflow_clone_dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    container_name: stackoverflow-clone-backend
    command: yarn run dev
    restart: on-failure

volumes:
  postgres-data:
