services:
  stackoverflow-db:
    image: postgres
    container_name: stackoverflow-db
    restart: on-failure
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  stackoverflow-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - stackoverflow-db
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DB_NAME=${DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB}
      - DB_PORT=${DB_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    container_name: stackoverflow-backend
    command: yarn run dev
    restart: on-failure

volumes:
  postgres-data:
